### ISSUE TITLE
Initial issue

### ISSUE THREAD

**Issue by Junior-16** [JeanCHilger/atsob#1]
Hello world friends

**Comment by henriqueherrera** [comment]
eae eae eae

**Comment by henriqueherrera** [comment]
preciso de alguma coisa para guardar numeros

**Comment by VectorialZombie** [comment]
isso nós temos de fazer ou vcs?

**Comment by Kellane** [comment]
acho que e data

**Comment by Kellane** [comment]
é alguma coisa pra guardar uma data de alguma coisa??

**Comment by VectorialZombie** [comment]
vcs fazem q ta no nosso quadro e nos fazemos o do teu acho
nao sei
